-- Blender-first preset consumed by libraries/ddd-3d.
-- Static transforms, hierarchy, and camera anchors live in kingbattle_scene.glb.
local metal_surface = {
    albedo = "textures/blue_metal_plate_diff_1k.jpg",
    normal = "textures/blue_metal_plate_nor_gl_1k.jpg",
    roughness = "textures/blue_metal_plate_rough_1k.jpg",
}
local degree = math.pi / 180
-- Keep the authored motion relationships while making the scene settle more slowly.
local motion_speed_scale = 0.60

return {
    version = 2,

    materials = {
        cage_metal = {
            name = "kingbattle_cage_metal",
            shader = "lit",
            base_color = { 0.72, 0.82, 1.00, 1.0 },
            emissive = { 0.002, 0.005, 0.016 },
            metallic = 0.78,
            roughness = 0.66,
            specular_strength = 0.34,
            ambient_reflection = 0.48,
            base_color_texture = metal_surface.albedo,
            normal_texture = metal_surface.normal,
            roughness_texture = metal_surface.roughness,
            normal_strength = 0.16,
            uv_scale = { 1.45, 1.45 },
            double_sided = true,
        },
        chain_metal = {
            name = "kingbattle_chain_metal",
            shader = "lit",
            base_color = { 0.36, 0.45, 0.62, 1.0 },
            emissive = { 0.001, 0.003, 0.009 },
            metallic = 0.82,
            roughness = 0.58,
            specular_strength = 0.30,
            ambient_reflection = 0.34,
            base_color_texture = metal_surface.albedo,
            normal_texture = metal_surface.normal,
            roughness_texture = metal_surface.roughness,
            normal_strength = 0.12,
            uv_scale = { 1.25, 1.25 },
            double_sided = true,
        },
        background_wall = {
            name = "kingbattle_background_wall",
            shader = "lit",
            base_color = { 0.62, 0.72, 0.96, 1.0 },
            emissive = { 0.006, 0.011, 0.027 },
            metallic = 0.24,
            roughness = 0.92,
            specular_strength = 0.12,
            ambient_reflection = 0.18,
            base_color_texture = metal_surface.albedo,
            normal_texture = metal_surface.normal,
            roughness_texture = metal_surface.roughness,
            normal_strength = 0.07,
            uv_scale = { 1.35, 0.90 },
            double_sided = true,
        },
        suit_edge = {
            name = "kingbattle_suit_edge",
            shader = "lit",
            base_color = { 0.48, 0.05, 0.95, 1.0 },
            emissive = { 0.165, 0.008, 0.510 },
            metallic = 0.38,
            roughness = 0.24,
            double_sided = true,
        },
        suit_fill = {
            name = "kingbattle_suit_fill",
            shader = "lit",
            base_color = { 0.006, 0.003, 0.018, 1.0 },
            emissive = { 0.001, 0.000, 0.006 },
            metallic = 0.16,
            roughness = 0.42,
            double_sided = true,
        },
    },

    authored_scene = {
        path = "kingbattle_scene.glb",
        -- The GLB keeps the editable Blender layout in native Z-up space.
        -- ddd-3d performs the one explicit B(x, y, z) -> E(x, -z, -y)
        -- conversion while instantiating the authored scene.
        coordinate_space = "blender_z_up",
        root = "DDD_SCENE_ROOT",
        required_nodes = {
            "DDD_SCENE_ROOT",
            "environment_shell",
            "cage",
            "pendant_club",
            "chain_club",
            "club",
            "pendant_spade",
            "chain_spade",
            "spade",
            "pendant_heart",
            "chain_heart",
            "heart",
            "pendant_diamond",
            "chain_diamond",
            "diamond",
            "anchor_camera",
            "anchor_camera_target",
            "anchor_fountain",
        },
        material_overrides = {
            background_wall = "background_wall",
            cage_metal = "cage_metal",
            chain_metal = "chain_metal",
            suit_edge = "suit_edge",
            suit_fill = "suit_fill",
        },
        camera = {
            anchor = "anchor_camera",
            target_anchor = "anchor_camera_target",
            fov = 0.7853981634,
            near = 0.10,
            far = 96.0,
        },
        motions = {
            -- The vertical chain axis stays fixed. Both layers rotate only
            -- around the authored horizontal swing axis.
            {
                node = "pendant_club",
                kind = "sway",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 2.2 * degree,
                speed = 0.62 * motion_speed_scale,
                phase = 0.65,
            },
            {
                node = "pendant_spade",
                kind = "sway",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 1.8 * degree,
                speed = 0.78 * motion_speed_scale,
                phase = 3.55,
            },
            {
                node = "pendant_heart",
                kind = "sway",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 2.5 * degree,
                speed = 0.70 * motion_speed_scale,
                phase = 4.75,
            },
            {
                node = "pendant_diamond",
                kind = "sway",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 2.0 * degree,
                speed = 0.88 * motion_speed_scale,
                phase = 2.10,
            },
            {
                node = "chain_club",
                kind = "chain_sway",
                terminal = "club",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 41 * degree,
                speed = 1.25 * motion_speed_scale,
                phase = 0.65,
                link_axis = { 0.0, 1.0, 0.0 },
                link_amplitude = 25 * degree,
                link_phase_lag = 0.70,
                link_min_weight = 0.07,
                link_curve = 1.40,
            },
            {
                node = "chain_spade",
                kind = "chain_sway",
                terminal = "spade",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 39 * degree,
                speed = 1.55 * motion_speed_scale,
                phase = 3.55,
                link_axis = { 0.0, 1.0, 0.0 },
                link_amplitude = 22 * degree,
                link_phase_lag = 0.58,
                link_min_weight = 0.09,
                link_curve = 1.25,
            },
            {
                node = "chain_heart",
                kind = "chain_sway",
                terminal = "heart",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 45 * degree,
                speed = 1.35 * motion_speed_scale,
                phase = 4.75,
                link_axis = { 0.0, 1.0, 0.0 },
                link_amplitude = 27 * degree,
                link_phase_lag = 0.76,
                link_min_weight = 0.06,
                link_curve = 1.45,
            },
            {
                node = "chain_diamond",
                kind = "chain_sway",
                terminal = "diamond",
                axis = { 0.0, 1.0, 0.0 },
                amplitude = 42 * degree,
                speed = 1.65 * motion_speed_scale,
                phase = 2.10,
                link_axis = { 0.0, 1.0, 0.0 },
                link_amplitude = 23 * degree,
                link_phase_lag = 0.64,
                link_min_weight = 0.08,
                link_curve = 1.32,
            },
        },
    },

    scene = {
        clear_color = { 0.005, 0.008, 0.020, 1.0 },
        light = {
            direction = { -0.30, -0.58, -0.76 },
            color = { 0.46, 0.57, 0.86, 1.0 },
            ambient = { 0.060, 0.085, 0.180, 1.0 },
            fill = {
                direction = { 0.46, -0.32, 0.72 },
                color = { 0.16, 0.20, 0.40 },
                strength = 0.18,
            },
        },
    },

    output = {
        clear_color = { 0.005, 0.008, 0.020, 1.0 },
        fog = {
            color = { 0.012, 0.022, 0.060 },
            strength = 0.035,
        },
        vignette = 0.16,
    },
}
